productJson = {
   "products":{
      "product":[
         {
            "modules":{
               "module":[
                  {
                     "id":"REA",
                     "name":"Reasons",
                     "symbol":"Reasons",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"INV",
                     "name":"Core Inventory",
                     "symbol":"CoreInv",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"NOT",
                     "name":"Notebook",
                     "symbol":"Notebook",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DIR",
                     "name":"Directory",
                     "symbol":"Directory",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PHS",
                     "name":"Physical Model",
                     "symbol":"Physical",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HCM",
            "name":"Common",
            "symbol":"Common",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"CPM",
                     "name":"Core Patient Model",
                     "symbol":"Core",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PHD",
                     "name":"Patient Header",
                     "symbol":"PatientHeader",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"ADT",
                     "name":"ADT",
                     "symbol":"ADT",
                     "jiraComponent":"ADT",
                     "generatePackage":"False"
                  },
                  {
                     "id":"IPM",
                     "name":"In-Patient Management",
                     "symbol":"InPatient",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"APP",
                     "name":"Appointments",
                     "symbol":"Appointments",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"WTL",
                     "name":"Waiting List",
                     "symbol":"WaitingList",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"REF",
                     "name":"Referrals",
                     "symbol":"Referrals",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"CLQ",
                     "name":"Call Queue",
                     "symbol":"CallQueue",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"WKQ",
                     "name":"Work Queue",
                     "symbol":"WorkQueue",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"MRC",
                     "name":"Medical Record",
                     "symbol":"MedRec",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PRT",
                     "name":"Portering",
                     "symbol":"Portering",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"VST",
                     "name":"Visitor",
                     "symbol":"Visitor",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DUT",
                     "name":"Data Upload Templates",
                     "symbol":"DataUploadTemplates",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"EDU",
                     "name":"Patient Education",
                     "symbol":"PatientEducation",
                     "jiraComponent":"Patient Education",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HPS",
            "name":"Patient Administration System",
            "symbol":"PAS",
            "jiraKey":"HPS",
            "wikiUrl":"http://woki/display/HIS/HPS"
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"CUP",
                     "name":"Checkup Report",
                     "symbol":"CheckupReport",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"CLD",
                     "name":"Clinical Documentation",
                     "symbol":"ClinDoc",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"CPK",
                     "name":"Core Package",
                     "symbol":"Core",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"CPO",
                     "name":"CPOE",
                     "symbol":"CPOE",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"EMR",
                     "name":"EMR",
                     "symbol":"EMR",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"GTW",
                     "name":"Gateway",
                     "symbol":"Gateway",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"MDC",
                     "name":"Medical Coding",
                     "symbol":"MedCoding",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"MWS",
                     "name":"MWS",
                     "symbol":"MWS",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SOT",
                     "name":"Signout Tab",
                     "symbol":"SignoutTab",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"STR",
                     "name":"Sructured Reports",
                     "symbol":"StructuredReports",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HCL",
            "name":"Clinical",
            "symbol":"Clinical",
            "jiraKey":"HCL",
            "wikiUrl":"http://woki/display/HIS/HCL"
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"MED",
                     "name":"Medication",
                     "symbol":"Medication",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"ORD",
                     "name":"Orders",
                     "symbol":"Orders",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DSP",
                     "name":"Dispensing",
                     "symbol":"Dispensing",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"MAR",
                     "name":"Medication Administration",
                     "symbol":"MedAdmin",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SCR",
                     "name":"Screening",
                     "symbol":"Screening",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"LBL",
                     "name":"Labeling",
                     "symbol":"Labeling",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"REP",
                     "name":"Reports",
                     "symbol":"Reports",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"COM",
                     "name":"Compounding",
                     "symbol":"Compounding",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"EXB",
                     "name":"Expression Builder",
                     "symbol":"ExpressionBuilder",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"VAC",
                     "name":"Vaccination",
                     "symbol":"Vaccination",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PAR",
                     "name":"Patient Adverse Reaction",
                     "symbol":"PatientAdverseReaction",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HPH",
            "name":"Pharmacy",
            "symbol":"Pharmacy",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"RIS",
                     "name":"RIS",
                     "symbol":"RIS",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PAC",
                     "name":"PACS",
                     "symbol":"PACS",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DIC",
                     "name":"DICOM",
                     "symbol":"DICOM",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HRP",
            "name":"Radiology",
            "symbol":"Radiology",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"IFC",
                     "name":"Interfacing",
                     "symbol":"Interfacing",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DUT",
                     "name":"Data Upload Templates",
                     "symbol":"DataUploadTemplates",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HLB",
            "name":"Laboratory",
            "symbol":"Lab",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"PRE",
                     "name":"Pre-Operative",
                     "symbol":"PreOp",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"INT",
                     "name":"Intra-Operative",
                     "symbol":"IntraOp",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PST",
                     "name":"Post-Operative",
                     "symbol":"PostOp",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HTM",
            "name":"Surgical Management",
            "symbol":"Surgical",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"COR",
                     "name":"Core Configuration",
                     "symbol":"Config",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"EMP",
                     "name":"Employee",
                     "symbol":"Employee",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PPL",
                     "name":"People",
                     "symbol":"People",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"AR",
                     "name":"Accounts Receivable",
                     "symbol":"AR",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"AP",
                     "name":"Accounts Payable",
                     "symbol":"AP",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"GL",
                     "name":"General Ledger",
                     "symbol":"GL",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"FA",
                     "name":"Fixed Assets",
                     "symbol":"FA",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"CM",
                     "name":"Cash Managment",
                     "symbol":"CM",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PF",
                     "name":"Patient Finance",
                     "symbol":"PF",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"INV",
                     "name":"Inventory",
                     "symbol":"Inventory",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PUR",
                     "name":"Purchasing",
                     "symbol":"Purchasing",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DMM",
                     "name":"Materials Management",
                     "symbol":"MM",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"CRE",
                     "name":"Caregiver Reimbursement",
                     "symbol":"CR",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HBO",
            "name":"Back Office",
            "symbol":"BackOffice",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"DSH",
                     "name":"Dashboard",
                     "symbol":"Dashboard",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"OLA",
                     "name":"OLAP",
                     "symbol":"OLAP",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HBI",
            "name":"Business Intelligence",
            "symbol":"BI",
            "jiraKey":"HBI",
            "wikiUrl":"http://woki/display/his/HBI"
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"ACC",
                     "name":"ActiveCare",
                     "symbol":"ActiveCare",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"AUD",
                     "name":"Auditing",
                     "symbol":"Auditing",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"BES",
                     "name":"Back-End Services",
                     "symbol":"Services",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DAF",
                     "name":"Data Access Framework",
                     "symbol":"DataAccess",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DUF",
                     "name":"Data Upload Framework",
                     "symbol":"DataUpload",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DUT",
                     "name":"Data Upload Templates",
                     "symbol":"DataUploadTemplates",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"DMG",
                     "name":"Document Management",
                     "symbol":"DocMan",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"COR",
                     "name":"Core Framework",
                     "symbol":"Framework",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"INS",
                     "name":"Installation",
                     "symbol":"Installation",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"INS2",
                     "name":"Installer",
                     "symbol":"Installer",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"IFC",
                     "name":"Interfacing",
                     "symbol":"Interfacing",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"HOS",
                     "name":"Hospital",
                     "symbol":"Hospital",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"LOC",
                     "name":"Localization",
                     "symbol":"Localization",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"MNT",
                     "name":"Maintenance",
                     "symbol":"Maintenance",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"MON",
                     "name":"Monitoring",
                     "symbol":"Monitoring",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PRN",
                     "name":"Printing",
                     "symbol":"Printing",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SHL",
                     "name":"Shell",
                     "symbol":"Shell",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SMR",
                     "name":"Scan Manager / SMR",
                     "symbol":"SMR",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SCH",
                     "name":"Scheduling",
                     "symbol":"Scheduling",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SEC",
                     "name":"Security",
                     "symbol":"Security",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SPM",
                     "name":"Speech Magic",
                     "symbol":"Speech",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"STR",
                     "name":"Structured Report Editor",
                     "symbol":"StructuredReports",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"STO",
                     "name":"Storage",
                     "symbol":"Storage",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"UIF",
                     "name":"UI Framework",
                     "symbol":"UIFramework",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"UIC",
                     "name":"UI Controls",
                     "symbol":"UIControls",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"WWF",
                     "name":"Windows Workflow Foundation",
                     "symbol":"WWF",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"WKQ",
                     "name":"Work Queue",
                     "symbol":"WorkQueue",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"CNF",
                     "name":"Consistency Framework",
                     "symbol":"CFX",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"PBX",
                     "name":"PABX Interfacing",
                     "symbol":"PBX",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"IMG",
                     "name":"Imaging Framework",
                     "symbol":"IMG",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SECLAB",
                     "name":"Security Label",
                     "symbol":"SecurityLabel",
                     "jiraComponent":"Security Label",
                     "generatePackage":"False"
                  },
                  {
                     "id":"INTREP",
                     "name":"Interactive Report",
                     "symbol":"InteractiveReport",
                     "jiraComponent":"Interactive Report",
                     "generatePackage":"False"
                  },
                  {
                     "id":"OBJLIB",
                     "name":"Object Library",
                     "symbol":"ObjectLibrary",
                     "jiraComponent":"Object Library",
                     "generatePackage":"False"
                  },
                  {
                     "id":"LIST",
                     "name":"List Framework",
                     "symbol":"ListFramework",
                     "jiraComponent":"List Framework",
                     "generatePackage":"False"
                  },
                  {
                     "id":"UNICOM",
                     "name":"Unified Communications",
                     "symbol":"UnifiedCommunications",
                     "jiraComponent":"Unified Communications",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HIF",
            "name":"Infrastructure",
            "symbol":"Inf",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"COR",
                     "name":"Core Test Framework",
                     "symbol":"Framework",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"UIA",
                     "name":"UI Automation Framework",
                     "symbol":"UIA",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HTI",
            "name":"Test Infrastructure",
            "symbol":"TestInf",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "id":"MISC",
            "name":"Miscellaneous",
            "symbol":"MISC",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "modules":{
               "module":[
                  {
                     "id":"UIA",
                     "name":"UI Test Framework",
                     "symbol":"UIA",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"TF",
                     "name":"Test Framework",
                     "symbol":"Framework",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"FF",
                     "name":"Fixture Framework",
                     "symbol":"FF",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  },
                  {
                     "id":"SDS",
                     "name":"Sample Data Studio",
                     "symbol":"SDS",
                     "jiraComponent":"",
                     "generatePackage":"False"
                  }
               ]
            },
            "id":"HDT",
            "name":"Hospital Dev Tools",
            "symbol":"HDT",
            "jiraKey":"",
            "wikiUrl":""
         },
         {
            "id":"HSMR",
            "name":"Scanned Medical Records",
            "symbol":"SMR",
            "jiraKey":"",
            "wikiUrl":""
         }
      ]
   }
}