/*
 * Copyright (c) Orchestral Developments Ltd (2001 - 2014).
 *
 * This document is copyright. Except for the purpose of fair reviewing, no part
 * of this publication may be reproduced or transmitted in any form or by any
 * means, electronic or mechanical, including photocopying, recording, or any
 * information storage and retrieval system, without permission in writing from
 * the publisher. Infringers of copyright render themselves liable for
 * prosecution.
 */
(function(){"use strict";function P(e,t){e.setAttribute(S,t)}function H(e,t,n){e.setAttribute(h+t,n)}function B(e,t,n){n.cfg.setProperty(p,!0),n.cfg.setProperty(O,n.get(_))}function j(e,t){t._menu.subscribe(b,B,t)}function F(e,t){H(t._button,d,e.newValue)}function I(e){var t=e._button.parentNode;e.set(p,!0),P(t,T),P(t.parentNode,T)}function q(e,t){var n=e.prevValue,r=e.newValue,i=t.length,s,o,u=!1;if(i>0)for(o=0;o<i;o+=1)s=t[o],!r&&!u&&!s.get(D)?(s._button.tabIndex=0,u=!0):s===r?s._button.tabIndex=0:s._button.tabIndex=-1;n&&H(n._button,d,!1),r&&H(r._button,d,!0)}function R(e){var t=e.length,n,r,i=!1,s=-1;if(t>0){for(r=0;r<t&&!i;r+=1)n=e[r],n.get(D)||(n._button.tabIndex>-1?i=!0:s<0&&(s=r));!i&&s>-1&&(e[s]._button.tabIndex=0)}}var e=YAHOO.lang,t=ORCHESTRAL.env.ua,n=YAHOO.widget.Button.prototype,r=n.initAttributes,i=ORCHESTRAL.widget.ButtonGroupBase.prototype,s=i.initAttributes,o=ORCHESTRAL.widget.CheckboxButtonGroup.prototype,u=o.addButton,a=ORCHESTRAL.widget.RadioButtonGroup.prototype,f=a.addButton,l=a.addButtons,c=t.gecko&&t.gecko>=1.9||t.ie&&t.ie>=8||!t.gecko||!t.ie,h="aria-",p="usearia",d="checked",v="type",m="menu",g="split",y="haspopup",b="render",w="radio",E="checkbox",S="role",x="checkedChange",T="presentation",N="element",C="group",k="radiogroup",L="checkedButtonChange",A="appendTo",O="labelledby",M="describedby",_="id",D="disabled";c&&(n.RADIO_DEFAULT_TITLE="",n.RADIO_CHECKED_TITLE="",n.CHECKBOX_DEFAULT_TITLE="",n.CHECKBOX_CHECKED_TITLE=""),e.augmentObject(n,{_setUseAria:function(e){var t=this.get(v),n=this._button;if(e)if(t===m||t===g)H(n,y,!0),this.on(A,j,this);else if(t===w||t===E)P(n,t),H(n,d,this.get(d)),t===E&&this.on(x,F,this)},initAttributes:function(t){this.setAttributeConfig(p,{value:t.usearia||c,validator:e.isBoolean,writeOnce:!0,method:this._setUseAria}),r.apply(this,arguments),c&&this.set(p,!0)}},!0),e.augmentObject(i,{_setLabelledBy:function(e){this.get(p)&&H(this.get(N),O,e)},_setDescribedBy:function(e){this.get(p)&&H(this.get(N),M,e)},initAttributes:function(t){this.setAttributeConfig(p,{value:t.usearia||c,validator:e.isBoolean,writeOnce:!0,method:this._setUseAria}),this.setAttributeConfig(O,{value:t.labelledby,validator:e.isString,method:this._setLabelledBy}),this.setAttributeConfig(M,{value:t.describedby,validator:e.isString,method:this._setDescribedBy}),s.apply(this,arguments),c&&this.set(p,!0)}},!0),e.augmentObject(o,{addButton:function(e){var t=u.call(this,e);return this.get(p)&&I(t),t},_setUseAria:function(e){e&&P(this.get(N),C)}},!0),e.augmentObject(a,{addButton:function(e){var t=f.call(this,e);return this.get(p)&&(I(t),t._button.tabIndex=t.get(d)?0:-1),t},addButtons:function(e){var t=l.call(this,e);return R(t),t},_setUseAria:function(e){e&&(P(this.get(N),k),this.on(L,function(e){q(e,this.getButtons())}))}},!0)})(),YAHOO.register("orchestral-button-aria",ORCHESTRAL.widget.Button,{version:"7.9",build:"0"});
