/*
 * Copyright (c) Orchestral Developments Ltd (2001 - 2014).
 *
 * This document is copyright. Except for the purpose of fair reviewing, no part
 * of this publication may be reproduced or transmitted in any form or by any
 * means, electronic or mechanical, including photocopying, recording, or any
 * information storage and retrieval system, without permission in writing from
 * the publisher. Infringers of copyright render themselves liable for
 * prosecution.
 */
function Page(){}function Form(e){this.form=e,this.isDirty=function(){var e=function(e){return e.replace(/\r\n/g,"\r").replace(/\n/g,"\r")};for(var t=0;t<this.form.elements.length;t++){var n=this.form.elements[t];if(n.className.toLowerCase().indexOf("derived")!=-1)continue;if("text"==n.type||"hidden"==n.type||"password"==n.type||"textarea"==n.type){if(n.value!=n.defaultValue&&e(n.value)!=e(n.defaultValue))return!0}else if("checkbox"==n.type||"radio"==n.type){if(n.checked!=n.defaultChecked)return!0}else if("select-one"==n.type||"select-multiple"==n.type)for(var r=0;r<n.options.length;r++){var i=n.options[r];if(i.selected!=i.defaultSelected&&i.value!="")return!0}}return!1},this.clean=function(){for(var e=0;e<this.form.elements.length;e++){var t=this.form.elements[e];if("text"==t.type||"hidden"==t.type||"password"==t.type||"textarea"==t.type)t.defaultValue=t.value;else if("checkbox"==t.type||"radio"==t.type)t.defaultChecked=t.checked;else if("select-one"==t.type||"select-multiple"==t.type)for(var n=0;n<t.options.length;n++){var r=t.options[n];r.defaultSelected=r.selected}}},this.getParameterList=function(){var e=new ParameterList;for(var t=0;t<this.form.elements.length;t++){var n=this.form.elements[t],r=n.name;if(n.className.toLowerCase().indexOf("derived")!=-1)continue;if("select-one"==n.type||"select-multiple"==n.type){for(var i=0;i<n.options.length;i++)n.options[i].selected&&e.addParameter(r,n.options[i].value);e.hasParameter(r)||e.addParameter(r,"")}else"checkbox"==n.type?n.value&&n.value!="on"?n.checked&&e.addParameter(r,n.value):e.addParameter(r,n.checked):"radio"==n.type?n.checked?e.setParameter(r,n.value):e.hasParameter(r)||e.addParameter(r,""):r!=""&&typeof r!="undefined"&&e.addParameter(r,n.value)}return e}}window.Page=Page,Page.excludedInputNames=[],Page.changed=!1,Page.isDirty=function(){if(Page.changed)return!0;for(var e=0;e<document.forms.length;e++)if((new Form(document.forms[e])).isDirty())return!0;return!1},Page.setDirty=function(){Page.changed=!0},Page.clean=function(){for(var e=0;e<document.forms.length;e++)(new Form(document.forms[e])).clean();Page.changed=!1},Page.getParameterList=function(){var e=new ParameterList;for(var t=0;t<document.forms.length;t++)e.addParameters((new Form(document.forms[t])).getParameterList());return e},window.Form=Form
