/*
 * Copyright (c) Orchestral Developments Ltd (2001 - 2014).
 *
 * This document is copyright. Except for the purpose of fair reviewing, no part
 * of this publication may be reproduced or transmitted in any form or by any
 * means, electronic or mechanical, including photocopying, recording, or any
 * information storage and retrieval system, without permission in writing from
 * the publisher. Infringers of copyright render themselves liable for
 * prosecution.
 */
function AbstractCheckDigitAlgorithm(){this.createCheckDigit=function(e){var t=new Array(e.length),n=0;for(var r=0;r<e.length;r++){var i=e.charAt(r);if(i>="0"&&i<="9")var s=i-"0";else var s=this.getInt(e.charAt(r));s!=-1&&(t[n++]=s)}var o=this.calculateCheckDigit(t,0,n);return o!=-1?this.getCheckChar(o):null}}function Mod11CheckDigitAlgorithm(){this.calculateCheckDigit=function(e,t,n){var r=this.calculateCheckSum(e,t,n);return r%=11,r==0&&(r=1),(11-r)%10},this.calculateCheckSum=function(e,t,n){var r=0;for(var i=0;i<n;i++){var s=n-i-1+t,o=e[s],u=i%6+2;r+=o*u}return r},this.getInt=function(e){var t=alpha.indexOf(e);return t==-1?-1:t+1},this.getCheckChar=function(e){return"0123456789".charAt(e)}}function Mod11(){}function RestrictedMod11CheckDigitAlgorithm(){this.mod11=new Mod11CheckDigitAlgorithm,this.calculateCheckDigit=function(e,t,n){var r=this.mod11.calculateCheckSum(e,t,n);return r%=11,r==0?-1:(11-r)%10},this.getInt=function(e){return this.mod11.getInt(e)},this.getCheckChar=function(e){return this.mod11.getCheckChar(e)}}function RestrictedMod11(){}function Mod11AlphaCheckDigitAlgorithm(){this.mod11=new Mod11CheckDigitAlgorithm,this.calculateCheckDigit=function(e,t,n){var r=this.mod11.calculateCheckSum(e,t,n);return r%=11,r==0?-1:r},this.getInt=function(e){var t=alpha.indexOf(e);return t==-1?-1:t+1},this.getCheckChar=function(e){return alpha.charAt(e-1)}}function Mod11Alpha(){}var alpha="ABCDEFGHJKLMNPQRSTUVWXYZ";window.AbstractCheckDigitAlgorithm=AbstractCheckDigitAlgorithm,window.Mod11CheckDigitAlgorithm=Mod11CheckDigitAlgorithm,Mod11CheckDigitAlgorithm.prototype=new AbstractCheckDigitAlgorithm,Mod11CheckDigitAlgorithm.prototype.constructor=Mod11CheckDigitAlgorithm,Mod11CheckDigitAlgorithm.superclass=AbstractCheckDigitAlgorithm.prototype;var MOD_11=new Mod11CheckDigitAlgorithm;window.Mod11=Mod11,Mod11.calculateCheckDigit=function(e){return MOD_11.createCheckDigit(e)},window.RestrictedMod11CheckDigitAlgorithm=RestrictedMod11CheckDigitAlgorithm,RestrictedMod11CheckDigitAlgorithm.prototype=new AbstractCheckDigitAlgorithm,RestrictedMod11CheckDigitAlgorithm.prototype.constructor=RestrictedMod11CheckDigitAlgorithm,RestrictedMod11CheckDigitAlgorithm.superclass=AbstractCheckDigitAlgorithm.prototype;var MOD_11_RESTRICTED=new RestrictedMod11CheckDigitAlgorithm;window.RestrictedMod11=RestrictedMod11,RestrictedMod11.calculateCheckDigit=function(e){return MOD_11_RESTRICTED.createCheckDigit(e)},window.Mod11AlphaCheckDigitAlgorithm=Mod11AlphaCheckDigitAlgorithm,Mod11AlphaCheckDigitAlgorithm.prototype=new AbstractCheckDigitAlgorithm,Mod11AlphaCheckDigitAlgorithm.prototype.constructor=RestrictedMod11CheckDigitAlgorithm,Mod11AlphaCheckDigitAlgorithm.superclass=AbstractCheckDigitAlgorithm.prototype;var MOD_11_ALPHA=new Mod11AlphaCheckDigitAlgorithm;window.Mod11Alpha=Mod11Alpha,Mod11Alpha.calculateCheckDigit=function(e){return MOD_11_ALPHA.createCheckDigit(e)};
