/*
 * Copyright (c) Orchestral Developments Ltd (2001 - 2014).
 *
 * This document is copyright. Except for the purpose of fair reviewing, no part
 * of this publication may be reproduced or transmitted in any form or by any
 * means, electronic or mechanical, including photocopying, recording, or any
 * information storage and retrieval system, without permission in writing from
 * the publisher. Infringers of copyright render themselves liable for
 * prosecution.
 */
YUI.add("ohp-tag",function(e,t){var n=e.OHP.Locale,r=".ohp-tag-content .icon-remove-tag",i,s;i=e.Base.create("ohp-tag",e.Widget,[e.WidgetChild],{ROOT_TYPE:s,BOUNDING_TEMPLATE:"<span />",CONTENT_TEMPLATE:"<span />",renderUI:function(){var t=this.get("parent").get("name"),n=this.get("contentBox"),r;n.setContent(this.get("label")),n.insert('<span class="icon-remove-tag"></span>'),t&&(r=e.substitute('<input type="hidden" name="{name}" value="{value}"/>',{name:t,value:this.get("value")}),n.insert(r))}},{CSS_PREFIX:"ohp-tag",ATTRS:{label:{value:"",validator:e.Lang.isString},value:{getter:function(e){return e?e:this.get("label")},writeOnce:!0,validator:e.Lang.isString}},HTML_PARSER:{label:function(e){return e.getContent()}}}),s=e.Base.create("ohp-tag-group",e.Widget,[e.WidgetParent],{BOUNDING_TEMPLATE:"<span />",CONTENT_TEMPLATE:null,initializer:function(t){t._htmlParsedChildren&&this._add(t._htmlParsedChildren),e.Do.after(this._appendFooter,this,"renderUI")},_appendFooter:function(){var t=e.substitute('<span class="{footerClass}"></span>',{footerClass:this.getClassName("footer")}),n=this.getClassName("footer"),r=this.get("contentBox");r.appendChild(t),this._footerNode=r.one("."+n)},bindUI:function(){this.get("contentBox").delegate("click",function(e){e.preventDefault(),this._onRemoveButtonClick(e.target)},r,this),this._footerNode.on("click",function(t){var n=this.get("changeHandler"),r;t.preventDefault(),n&&(r=e.bind(n,this),r())},this),this.after("addChild",this.syncUI),this.after("removeChild",this.syncUI)},_syncFooter:function(){var e=this._footerNode.next(!1);e&&this._footerNode.swap(e)},syncUI:function(){var t=e.substitute('<a href="#">{change}</a>',{change:n.get("widget.tag.action.change")});this.isEmpty()?(this.get("boundingBox").addClass(this.getClassName("empty")),t=e.substitute('<a href="#">{add}</a>',{add:n.get("widget.tag.action.add")}),this.onceAfter("addChild",this._syncFooter)):(this.get("boundingBox").removeClass(this.getClassName("empty")),t=e.substitute('<a href="#">{change}</a>',{change:n.get("widget.tag.action.change")})),this._footerNode.setContent(t)},_onRemoveButtonClick:function(e){var t=this.get("contentBox").all(r).indexOf(e);this.remove(t)},_footerNode:null},{CSS_PREFIX:"ohp-tag-group",ATTRS:{defaultChildType:{value:i,readOnly:!0},changeHandler:{value:function(){},validator:e.Lang.isFunction,writeOnce:!0},name:{writeOnce:!0,validator:e.Lang.isString}},HTML_PARSER:{_htmlParsedChildren:function(e){var t=e.all("span"),n=[];return t.each(function(e){n.push({srcNode:e})}),n}}}),e.namespace("OHP").TagGroup=s},"7.9.0",{requires:["ohp-locale-translations","ohp-locale-base","arraylist","widget-child","base","substitute","node-event-delegate","widget","event-base","oop","node-base","widget-parent"]});
