/*
 * Copyright (c) Orchestral Developments Ltd (2001 - 2014).
 *
 * This document is copyright. Except for the purpose of fair reviewing, no part
 * of this publication may be reproduced or transmitted in any form or by any
 * means, electronic or mechanical, including photocopying, recording, or any
 * information storage and retrieval system, without permission in writing from
 * the publisher. Infringers of copyright render themselves liable for
 * prosecution.
 */
YAHOO.namespace("ORCHESTRAL.util"),ORCHESTRAL.util.Dom=function(){"use strict";var e=YAHOO.util.Dom,t=1,n={TABLE:["<table>","</table>",1],TBODY:["<table><tbody>","</tbody></table>",2],THEAD:["<table><thead>","</thead></table>",2],TFOOT:["<table><tfoot>","</tfoot></table>",2],TR:["<table><tbody><tr>","</tr></tbody></table>",3],SELECT:["<select>","</select>",1]},r=/(?:<script.*?>)((\n|\r|.)*?)(?:<\/script>)/img,i=[],s=function(t){var n=t;while(n&&n.tagName!=="BODY")e.getStyle(n,"display")==="none"&&(i.push({element:n,visibility:YAHOO.util.Dom.getStyle(n,"visibility"),display:YAHOO.util.Dom.getStyle(n,"display")}),e.setStyle(n,"visibility","hidden"),e.setStyle(n,"display","block")),n=n.parentNode},o=function(){var t=i.pop();while(t)e.setStyle(t.element,"visibility",t.visibility),e.setStyle(t.element,"display",t.display),t=i.pop()},u=function(t){t=e.get(t);var n=t.childNodes.length,r;for(r=0;r<n;r+=1)ORCHESTRAL.util.Dom.remove(t.childNodes[0],!0)},a=function(t,n){t=t.replace(r,"");var i=document.createElement("div"),s=[],o=i,a,f;i.innerHTML=n?n[0]+t+n[1]:t;if(n)for(a=0;a<n[2];a+=1)o=e.getFirstChild(o);f=o.childNodes.length;for(a=0;a<f;a+=1)s[a]=o.childNodes[a];return u(i),i=null,s},f=function(r,i,s){r=e.get(r);var o=null,u=a(i,n[r.parentNode.tagName]),f,l=u.length,c;for(c=0;c<l;c+=1)f=u[c],s(f,r),!o&&f.nodeType===t&&(o=f);return o};return{getDimensions:function(t){t=e.get(t),s(t);var n=t.offsetWidth,r=t.offsetHeight;return o(),{width:n,height:r}},getHeight:function(e){return ORCHESTRAL.util.Dom.getDimensions(e).height},getWidth:function(e){return ORCHESTRAL.util.Dom.getDimensions(e).width},resizeTo:function(t,n,r){n&&(e.setStyle(t,"width",n+"px"),e.setStyle(t,"width",n+(n-ORCHESTRAL.util.Dom.getWidth(t))+"px")),r&&(e.setStyle(t,"height",r+"px"),e.setStyle(t,"height",r+(r-ORCHESTRAL.util.Dom.getHeight(t))+"px"))},remove:function(t,n){t=e.get(t);if(t)return t.parentNode.removeChild(t),n&&YAHOO.util.Event.purgeElement(t,!1),t;return},insertHtmlBefore:function(t,n){return f(t,n,e.insertBefore)},insertHtmlAfter:function(t,n){return f(t,n,e.insertAfter)},insertHtmlAsFirstChild:function(t,n){return ORCHESTRAL.util.Dom.insertHtmlBefore(e.getFirstChild(t),n)},insertHtmlAsLastChild:function(t,n){return ORCHESTRAL.util.Dom.insertHtmlAfter(e.getLastChild(t),n)},isElement:function(e){return typeof HTMLElement=="object"?e instanceof HTMLElement:YAHOO.lang.isObject(e)&&e.nodeType===t&&YAHOO.lang.isString(e.nodeName)},setInnerHtml:function(t,i){t=e.get(t);if(n[t.tagName]){u(t);var s=a(i,n[t.tagName]),o=s.length,f;for(f=0;f<o;f+=1)t.appendChild(s[f])}else t.innerHTML=i.replace(r,"");return e.getFirstChild(t)},setText:document.documentElement.textContent!==undefined?function(t,n){e.get(t).textContent=n}:function(t,n){e.get(t).innerText=n}}}(),YAHOO.register("orchestral-dom",ORCHESTRAL.util.Dom,{version:"7.9",build:"0"});
